version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo-{{ checksum "Cargo.toml" }}
      - run:
          name: Nightly Build
          command: |
            rustup install nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: cargo-{{ checksum "Cargo.toml" }}
          paths:
            - "~/.cargo"
            - "./target"