version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo-{{ checksum "Cargo.toml" }}
      - run:
          name: Refresh rustup
          command: |
            rustup self uninstall
            curl https://sh.rustup.rs -sSf | sh
      - run:
          name: Nightly Build
          command: |
            rustup install nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Clippy
          command: |
            rustup component add clippy
            rustup run nightly cargo clippy
      - run:
          name: Test
          command: rustup run nightly cargo test
      - save_cache:
          key: cargo-{{ checksum "Cargo.toml" }}
          paths:
            - "~/.cargo"
            - "./target"