version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo-{{ checksum "Cargo.toml" }}
      - run:
          name: Nightly Build
          command: |
            rustup default nightly
            rustc --version --verbose
            cargo --version --verbose
            cargo build
      - run:
          name: Clippy
          command: |
            rustup component add clippy
            cargo clippy
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: cargo-{{ checksum "Cargo.toml" }}
          paths:
            - "~/.cargo"
            - "./target"