[package]
name = "josefine-raft"
version = "0.0.1"
authors = ["jcm <jmcelwain@gmail.com>"]
edition = "2018"

[dependencies]
slog = { version = "2.4.1", features = ["max_level_debug"]}
slog-async = "2.3.0"
slog-term = "2.4.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0"
rand = "0.6"
tokio = "0.1.17"
actix = "0.7"
backoff = "0.1.5"
lazy_static = "1.3.0"
snafu = "0.4.1"
config = "0.9"
