[package]
name = "josefine-raft"
version = "0.0.1"
authors = ["jcm <jmcelwain@gmail.com>"]
edition = "2018"

[dependencies]
slog = "2.4.1"
slog-async = "2.3.0"
slog-term = "2.4.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0"
