[package]
name = "josefine-cli"
version = "0.1.0"
authors = ["jcm <jmcelwain@gmail.com>"]
edition = "2018"

[dependencies]
nom = "4.1.1"
clap = "2.32.0"
rustyline = "3.0.0"
josefine-raft = { version = "0.0.1", path = "../josefine-raft" }
serde = "1.0.84"
serde_json = "1.0"
